### ISSUE TITLE
netctl policy list --all/-a does not show policies created for a tenant

### ISSUE THREAD

**Issue by rkharya** [contiv/netplugin#329] opened 2016-04-17 16:28 UTC
[cluster-admin@contiv-aci-scale-2 ~]$ netctl policy create prod_web --tenant=Contiv_Scale
INFO[0000] Creating policy Contiv_Scale:prod_web

[cluster-admin@contiv-aci-scale-2 ~]$ netctl policy list  <<<<<<<<< This is expected
Tenant  Policy
------  ------
[cluster-admin@contiv-aci-scale-2 ~]$ netctl policy list -a  <<<<<<<< This is NOT expected

[cluster-admin@contiv-aci-scale-2 ~]$ netctl policy list --tenant=Contiv_Scale <<<< We need to specify tenant here....>>>>>>>>>>>
Tenant        Policy
------        ------
Contiv_Scale  prod_web

For example for network created for a specific tenant '-a' works -

[cluster-admin@contiv-aci-scale-2 ~]$ netctl net ls -a
Tenant        Network     Encap type  Packet tag  Subnet         Gateway
------        -------     ----------  ----------  -------        ------
Contiv_Scale  contiv-net  vlan        0           172.16.0.0/20  172.16.15.254

**Comment by shaleman** [comment] 2016-05-18 18:20
Duplicate of #318

**Closed by shaleman** 2016-05-18 18:20 UTC
