### ISSUE TITLE
Netplugin panic on K8S when running pods with Contiv CNI plugin

### ISSUE THREAD

**Issue by lainra** [contiv/netplugin#913] opened 2017-07-04 18:51 UTC
--------------------------------------------------------
BUG REPORT INFORMATION
------------------------------------------------------------------------------
--> Hello,

I found a bug with netplugin when running Contiv v1.0.3 on K8S v1.6.3 on Centos 7.3.
I'm using a modified Kargo to install K8S.
I've been troubleshooting this bug with @neelimamukiri on slack and am creating a bug issue here as the following of our discussion.  
There is no problem with the Contiv Install, configuration or the K8S cluster.
I managed to catch the error in netplugin log (i had to tail it become log are destroyed upon start of a new netplugin instance) :
```
2017/06/26 13:59:18 Unhandled Field: 105 in Class: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x86a206]

goroutine 85 [running]:
panic(0x172f280, 0xc42001a070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*MatchField).UnmarshalBinary(0xc420ebbd30, 0xc4208fb824, 0x93, 0x7dc, 0x1, 0xc4211df4a0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:160 +0x136
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*Match).UnmarshalBinary(0xc420388f18, 0xc4208fb818, 0x9f, 0x7e8, 0xa0, 0x18aaea0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:89 +0x12f
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*PacketIn).UnmarshalBinary(0xc420388f00, 0xc4208fb800, 0xb7, 0x800, 0xc41ffe0565, 0xc4208e2690)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:351 +0x25d
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.Parse(0xc4208fb800, 0xb7, 0x800, 0xc42008e5a0, 0x193de39, 0x8, 0xc4208e2770)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:135 +0x4be
github.com/contiv/netplugin/vendor/github.com/contiv/ofnet/ofctrl.(*Controller).Parse(0xc4209abe00, 0xc4208fb800, 0xb7, 0x800, 0x1, 0xc420231d08, 0x0, 0x0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/contiv/ofnet/ofctrl/ofctrl.go:184 +0x54
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.(*MessageStream).parse(0xc42008eaa0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:149 +0x19f
created by github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.NewMessageStream
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:68 +0x20d
```
The fact is that it makes Contiv extremely unstable when running pods with the Contiv CNI plugin.

When freshly launched, the cluster is doing well :
```
[root@k8s-contiv-m1 ~]# kubectl get po --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP               NODE
kube-system   contiv-api-proxy-z92j2                  1/1       Running   5          15m       192.168.40.191   k8s-contiv-m1
kube-system   contiv-etcd-6vtnx                       1/1       Running   0          15m       192.168.40.191   k8s-contiv-m1
kube-system   contiv-netmaster-q2k50                  1/1       Running   0          15m       192.168.40.191   k8s-contiv-m1
kube-system   contiv-netplugin-5skcq                  1/1       Running   0          15m       192.168.40.189   k8s-contiv-inf1
kube-system   contiv-netplugin-5x3wr                  1/1       Running   0          15m       192.168.40.134   k8s-contiv-m3
kube-system   contiv-netplugin-8dk70                  1/1       Running   0          15m       192.168.40.70    k8s-contiv-lb1
kube-system   contiv-netplugin-9rc41                  1/1       Running   0          15m       192.168.40.26    k8s-contiv-lb2
kube-system   contiv-netplugin-fmd09                  1/1       Running   0          15m       192.168.40.10    k8s-contiv-sb1
kube-system   contiv-netplugin-fqk7r                  1/1       Running   0          15m       192.168.40.94    k8s-contiv-inf2
kube-system   contiv-netplugin-frc6s                  1/1       Running   0          15m       192.168.40.44    k8s-contiv-m2
kube-system   contiv-netplugin-gsqzh                  1/1       Running   0          15m       192.168.40.19    k8s-contiv-s2
kube-system   contiv-netplugin-kk6qr                  1/1       Running   0          15m       192.168.40.23    k8s-contiv-s3
kube-system   contiv-netplugin-nwl3g                  1/1       Running   0          15m       192.168.40.141   k8s-contiv-s1
kube-system   contiv-netplugin-tft2v                  1/1       Running   0          15m       192.168.40.191   k8s-contiv-m1
kube-system   kube-apiserver-k8s-contiv-m1            1/1       Running   0          16m       192.168.40.191   k8s-contiv-m1
kube-system   kube-apiserver-k8s-contiv-m2            1/1       Running   0          16m       192.168.40.44    k8s-contiv-m2
kube-system   kube-apiserver-k8s-contiv-m3            1/1       Running   0          16m       192.168.40.134   k8s-contiv-m3
kube-system   kube-controller-manager-k8s-contiv-m1   1/1       Running   1          16m       192.168.40.191   k8s-contiv-m1
kube-system   kube-controller-manager-k8s-contiv-m2   1/1       Running   0          16m       192.168.40.44    k8s-contiv-m2
kube-system   kube-controller-manager-k8s-contiv-m3   1/1       Running   2          16m       192.168.40.134   k8s-contiv-m3
kube-system   kube-proxy-k8s-contiv-inf1              1/1       Running   0          16m       192.168.40.189   k8s-contiv-inf1
kube-system   kube-proxy-k8s-contiv-inf2              1/1       Running   0          16m       192.168.40.94    k8s-contiv-inf2
kube-system   kube-proxy-k8s-contiv-lb1               1/1       Running   0          16m       192.168.40.70    k8s-contiv-lb1
kube-system   kube-proxy-k8s-contiv-lb2               1/1       Running   0          16m       192.168.40.26    k8s-contiv-lb2
kube-system   kube-proxy-k8s-contiv-m1                1/1       Running   0          16m       192.168.40.191   k8s-contiv-m1
kube-system   kube-proxy-k8s-contiv-m2                1/1       Running   0          16m       192.168.40.44    k8s-contiv-m2
kube-system   kube-proxy-k8s-contiv-m3                1/1       Running   0          16m       192.168.40.134   k8s-contiv-m3
kube-system   kube-proxy-k8s-contiv-s1                1/1       Running   0          16m       192.168.40.141   k8s-contiv-s1
kube-system   kube-proxy-k8s-contiv-s2                1/1       Running   0          16m       192.168.40.19    k8s-contiv-s2
kube-system   kube-proxy-k8s-contiv-s3                1/1       Running   0          16m       192.168.40.23    k8s-contiv-s3
kube-system   kube-proxy-k8s-contiv-sb1               1/1       Running   0          16m       192.168.40.10    k8s-contiv-sb1
kube-system   kube-scheduler-k8s-contiv-m1            1/1       Running   0          16m       192.168.40.191   k8s-contiv-m1
kube-system   kube-scheduler-k8s-contiv-m2            1/1       Running   1          16m       192.168.40.44    k8s-contiv-m2
kube-system   kube-scheduler-k8s-contiv-m3            1/1       Running   1          16m       192.168.40.134   k8s-contiv-m3
kube-system   nginx-proxy-k8s-contiv-inf1             1/1       Running   0          16m       192.168.40.189   k8s-contiv-inf1
kube-system   nginx-proxy-k8s-contiv-inf2             1/1       Running   0          16m       192.168.40.94    k8s-contiv-inf2
kube-system   nginx-proxy-k8s-contiv-lb1              1/1       Running   0          16m       192.168.40.70    k8s-contiv-lb1
kube-system   nginx-proxy-k8s-contiv-lb2              1/1       Running   0          16m       192.168.40.26    k8s-contiv-lb2
kube-system   nginx-proxy-k8s-contiv-s1               1/1       Running   0          16m       192.168.40.141   k8s-contiv-s1
kube-system   nginx-proxy-k8s-contiv-s2               1/1       Running   0          16m       192.168.40.19    k8s-contiv-s2
kube-system   nginx-proxy-k8s-contiv-s3               1/1       Running   0          16m       192.168.40.23    k8s-contiv-s3
kube-system   nginx-proxy-k8s-contiv-sb1              1/1       Running   0          16m       192.168.40.10    k8s-contiv-sb1
```

After setting Contiv to routing mode :

```
[root@k8s-cisco-m1 ~]# grep fwdMode /var/contiv/log/netplugin.log
time="Jun 27 04:42:14.750556155" level=info msg="Received request to create new ovs switch bridge:contivVxlanBridge, localIP:192.168.40.101, fwdMode:bridge" 
time="Jun 27 04:42:15.763891881" level=info msg="Received request to create new ovs switch bridge:contivVlanBridge, localIP:192.168.40.101, fwdMode:bridge" 
time="Jun 27 04:43:35.905743294" level=info msg="Received request to create new ovs switch bridge:contivVxlanBridge, localIP:192.168.40.101, fwdMode:routing" 
time="Jun 27 04:43:36.914486935" level=info msg="Received request to create new ovs switch bridge:contivVlanBridge, localIP:192.168.40.101, fwdMode:routing" 
``` 

and creating the 2 default mandatory networks :

```
[root@k8s-cisco-m1 ~]# netctl net create -n infra -s 132.1.1.0/24 -g 132.1.1.1 contivh1
Creating network default:contivh1
[root@k8s-cisco-m1 ~]# netctl net create -n data -s 20.1.1.0/24 -g 20.1.1.1 default-net
Creating network default:default-net
[root@k8s-cisco-m1 ~]# 
```

I schedule my Kube-dns which runns on contiv-inf1 and get 2 panics, in 30 seconds inteval :

```
2017/06/27 04:50:46 Unhandled Field: 105 in Class: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x86a206]
goroutine 67 [running]:
panic(0x172f280, 0xc42001a070)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*MatchField).UnmarshalBinary(0xc4208fdd30, 0xc4202ee824, 0x65, 0x7dc, 0x1, 0xc4207005a0)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:160 +0x136
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*Match).UnmarshalBinary(0xc4202df378, 0xc4202ee818, 0x71, 0x7e8, 0xa0, 0x18aaea0)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:89 +0x12f
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*PacketIn).UnmarshalBinary(0xc4202df360, 0xc4202ee800, 0x89, 0x800, 0xc41ffced91, 0xc4204c9690)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:351 +0x25d
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.Parse(0xc4202ee800, 0x89, 0x800, 0xc420018640, 0x193de39, 0x8, 0xc4204c9770)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:135 +0x4be
github.com/contiv/netplugin/vendor/github.com/contiv/ofnet/ofctrl.(*Controller).Parse(0xc4202510e0, 0xc4202ee800, 0x89, 0x800, 0x1, 0xc4206568f8, 0x0, 0x0)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/contiv/ofnet/ofctrl/ofctrl.go:184 +0x54
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.(*MessageStream).parse(0xc42015bef0)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:149 +0x19f
created by github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.NewMessageStream
/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:68 +0x20d
```

and

```
2017/06/27 04:51:19 Unhandled Field: 33 in Class: 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x86a206]
goroutine 56 [running]:
panic(0x172f280, 0xc42001a070)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*MatchField).UnmarshalBinary(0xc420041d30, 0xc420169024, 0x70, 0x7dc, 0x1, 0xc4203c5f20)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:160 +0x136
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*Match).UnmarshalBinary(0xc4201d2298, 0xc420169018, 0x7c, 0x7e8, 0xa0, 0x18aaea0)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/match.go:89 +0x12f
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.(*PacketIn).UnmarshalBinary(0xc4201d2280, 0xc420169000, 0x94, 0x800, 0xc41ffce28b, 0xc42002ce90)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:351 +0x25d
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13.Parse(0xc420169000, 0x94, 0x800, 0xc420018640, 0x193de39, 0x8, 0xc42002cf70)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/openflow13/openflow13.go:135 +0x4be
github.com/contiv/netplugin/vendor/github.com/contiv/ofnet/ofctrl.(*Controller).Parse(0xc4202f16e0, 0xc420169000, 0x94, 0x800, 0x1, 0x0, 0x0, 0x0)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/contiv/ofnet/ofctrl/ofctrl.go:184 +0x54
github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.(*MessageStream).parse(0xc42014fbd0)
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:149 +0x19f
created by github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.NewMessageStream
    /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:68 +0x20d
```
## Steps to Reproduce (for bugs)

1. Install a  K8S cluster either with kubeadm or kargo
2. Install Contiv as described in Contiv/Install for K8S 1.6
3. Do the K8S 1.6 container networking tutorial available on contiv.github.io
4. Create a kube-dns pod, or any other pod which use the CNI Contiv plugin.

The kube-dns should lose his IP and network interface after a while, because the netplugin went on go panic. 

You can see with @neelimamukiri for further details.
I  think this issue  is related with  #891 as there are same symptoms.

Sincerely,

Lain92

**Comment by rchirakk** [comment] 2017-07-05 23:17
@Lain92  was there any local changes done in netplugin source code ?
Or did you configure/modify OVS in this setup ?

**Comment by Dilandeau** [comment] 2017-07-20 10:28
Hi @rchirakk there was no change done on the netplugin source code or OVS configuration in this setup

**Comment by g1rana** [comment] 2017-10-06 17:34
duplicate of #891

**Closed** 2020-09-03 06:31 UTC
