### ISSUE TITLE
netctl : when used with app-profile option, auto completion does not work

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#336] opened 2016-04-27 06:20 UTC
When you use netctl command with app-profile option, auto completion does not work. It works with other options like global, network, tenant etc.

**Comment by abhinandanpb** [comment] 2016-10-31 22:58
duplicate of - https://github.com/contiv/netplugin/issues/422

**Closed by abhinandanpb** 2016-10-31 22:58 UTC
