### ISSUE TITLE
Unable to create a profile in multiple vrf scenario

### ISSUE THREAD

**Issue by santosh76** [contiv/netplugin#429] opened 2016-06-24 19:13 UTC
I created a tenant TestDockerTenant : 
Manually I create vrf,bd,app-profile and epg and bound them on APIC. This is meant for non-contiv config : They are
TestVRF,TestBD,Testdbprofile,TestEPG. 

Now I manually created another VRF,BD for contiv testing : TestDockerTenant-VRF, TestDockerBD. 
I specified TestDockerBD as BD in cfg.yml file and re-ran net-demo. The swarm cluster came up fine. 

I executed the following netctl commands . Still the app-profile did not get created on APIC. 

netctl global set -f aci -v 1001-3000
netctl tenant create TestDockerTenant
netctl net create -t=TestDockerTenant -s 20.1.1.0/24 -g 20.1.1.254 -e vlan TestDockerBD
netctl group create -t=TestDockerTenant TestDockerBD TestDockerEPG
netctl group create -t=TestDockerTenant TestDockerBD TestDockerEPG1
netctl app-profile create -t TestDockerTenant -g TestDockerEPG1,TestDockerEPG TestDockerAppProfile

**Comment by jainvipin** [comment] 2016-06-25 06:20
@santosh76 - thanks for raising the issue
@gaurav-dalvi @jojimt - can you please let @santosh76 know how to get the aci-gw logs so we know what APIC responded back with and if the API calls were made correctly.

**Comment by gaurav-dalvi** [comment] 2016-06-28 03:07
@saramach : Can you please take a look at this one ?

We see this error when we push app-profile.

Tenant TestDockerTenant already exists.
Creating application profile TestDockerAppProfile in tenant TestDockerTenant
127.0.0.1 - - [28/Jun/2016 03:03:01] "POST /createAppProf HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/cobra/apicagent.py", line 802, in create_api
    ret = setupApp(jsData, apicMoDir)
  File "/cobra/apicagent.py", line 614, in setupApp
    apicMoDir.commit(cR)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_1h-py2.7.egg/cobra/mit/access.py", line 58, in commit
    return self._accessImpl.post(configObject)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_1h-py2.7.egg/cobra/internal/rest/accessimpl.py", line 175, in post
    return self.__parseError(rsp, CommitError, rsp.status_code)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_1h-py2.7.egg/cobra/internal/rest/accessimpl.py", line 181, in __parseError
    parseXMLError(rsp.text, errorClass, httpCode)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_1h-py2.7.egg/cobra/mit/xmlcodec.py", line 15, in parseXMLError
    raise errorClass(int(errorCode), errorStr, httpCode)
CommitError: property tnFvBDName of uni/tn-TestDockerTenant/ap-TestDockerAppProfile/epg-TestDockerEPG/rsbd failed validation for value 'uni/tn-TestDockerTenant/BD-TestDockerBD'

**Comment by saramach** [comment] 2016-06-28 05:02
Looks like the input is wrong.
Please send me the cfg.yml file. 'uni/tn-TestDockerTenant/BD-TestDockerBD' is not a valid BD name.
Please just have TestDockerBD in cfg.yml

Thanks
-Satish

**Comment by gaurav-dalvi** [comment] 2016-06-28 19:47
@santosh76 : Looks like we dont see this issue. Could you please confirm and close this one ?

**Comment by abhinandanpb** [comment] 2016-10-31 22:55
Lets reopen if the issue is seens again.

**Closed by abhinandanpb** 2016-10-31 22:55 UTC
