### ISSUE TITLE
Ports are not getting exposed with contiv networks having gateway and pkt_tag

### ISSUE THREAD

**Issue by pradvara** [contiv/netplugin#333] opened 2016-04-21 18:18 UTC
I have created two networks

[root@vm1 mongo_db]# netctl net create --subnet=21.1.1.0/24 test-net
[root@vm1 mongo_db]# netctl net create --subnet=22.1.1.0/24 --gateway=22.1.1.254 --pkt-tag=2201 demo-net

When container is created on the first network, the ports are getting exposed

[root@vm1 mongo_db]# docker run --net="test-net" -d -p 9031:27017 mongo_new
docker ps
d9dc8bcdf734e67ccb875f8d1f32d629ab83766ec7cff45d98ed4ea85fe3423d
[root@vm1 mongo_db]# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                           NAMES
d9dc8bcdf734        mongo_new                      "/usr/bin/mongod"        7 seconds ago       Up 2 minutes        10.106.240.56:9031->27017/tcp   vm1/thirsty_joliot

When the container is created using the second network, the ports are not getting exposed...
[root@vm1 mongo_db]# docker run --net="demo-net" -d -p 9032:27017 mongo_new
docker ps
b3ee570a6654234e898d07fd0293564d168761e9984e381a58a5c9229c89a862
[root@vm1 mongo_db]# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED              STATUS              PORTS                           NAMES
b3ee570a6654        mongo_new                      "/usr/bin/mongod"        3 seconds ago        Up 2 minutes                                        vm1/suspicious_swirles

**Comment by jainvipin** [comment] 2016-04-21 18:26
@pradvara - The behavior is expected; port mapping i.e. `-p` option is not needed in second option, because we expect that external gateway would handle this; now if external gateway is not-reachable or not configured then it wouldn't work like it is in your case.
The expectation is that the port mapping is not needed in non vxlan modes, which provides better integration for external connectivity without having to do port-mappings.

**Comment by jainvipin** [comment] 2016-04-21 19:05
one can also use `docker network connect` - this is inline with how things happen at docker.

**Comment by pradvara** [comment] 2016-04-28 07:26
Thank you Vipin for the clarification

**Comment by shaleman** [comment] 2016-04-28 18:40
Closing this since its expected behavior

**Closed by shaleman** 2016-04-28 18:40 UTC
